### ISSUE TITLE
Error 190: The pipe has been ended

### ISSUE THREAD

**Issue by tstiemerling** [poidasmith/winrun4j#72]
Any ideas how to stop this error occurring? Running java app on windows 7. Happens when we stop the service.

Follow on question: how does winrun4j terminate the application when the service is told to stop?

**Comment by neandrake** [comment]
Where are you seeing this error? Is it from Java exception or is it in WinRun4J logs or in the Windows Event Viewer? It sounds like perhaps some resource isn't being closed out properly when the service is told to stop - or the process isn't responding as expected.

For the followup:
1. Windows sends WinRun4J service-executable control message.
2. WinRun4J forwards this control request to the `serviceRequest` method on your implementation of the `org.boris.winrun4j.Service` interface you registered.

This allows you to receive the shutdown request. Compare the control code with the constants in the the `Service` interface. These should correspond to Microsoft documentation on service controls.

**Comment by tstiemerling** [comment]
Thanks for the response.

We are seeing the error as a popup when stopping the service using the
service manager. Here is the dialog:

[image: Inline image 5]


Here is what is in winrun_log.txt:

[info] ServiceCtrlHandler: 1
[info] Application exited (0).

We do not have any winrun4j classes, we are just using winrun4j to run our
Main method.
Possibly that is the issue, since our code does not exit cleanly when the
service is stopped.

Thanks, Tom

**Comment by neandrake** [comment]
I don't think the image got attached. Can you attach the winrun4j logs as well as check any logs from your java application?

**Comment by tstiemerling** [comment]
Thanks. Fixed this by adding a shim class implementing the Service
interface.
The issue is that the default MainService class calls System.exit() without
returning from the serviceRequest method, so SVC connection is not cleaned
up (and results in pipe error).

On Fri, Jul 17, 2015 at 2:48 PM, Christopher Speck <notifications@github.com

**Comment by neandrake** [comment]
Good find!

I'm guessing the MainService implementation exists as a reference implementation - System.exit() shouldn't be called during serviceRequest() but the JVM does need to shut down, the details for doing that being application-specific.

**Comment by neandrake** [comment]
Are you able to close this issue since it is resolved?
